name: simple_json
description: Simple way to dynamically convert from and to JSON using build-time generators given a type.
version: 1.2.1
homepage: https://github.com/FlutterDevTools/simple_json/tree/master/simple_json
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_resolvers: ^1.5.4
  analyzer: ^1.1.0
  build: ^1.6.3
  source_gen: ^0.9.10+3
  path: ^1.8.0
  glob: ^2.0.0

  simple_json_mapper:
    git:
      url: git://github.com/sgehrman/simple_json
      path: simple_json_mapper

dev_dependencies:
  build_runner: ^1.11.5
