name: simple_json
description: Simple way to dynamically convert from and to JSON using build-time generators given a type.
version: 1.2.1
homepage: https://github.com/FlutterDevTools/simple_json/tree/master/simple_json
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_resolvers: ^2.0.2
  analyzer: ^1.7.0
  build: ^2.0.1
  source_gen: ^1.0.1
     

  path: ^1.8.0
  glob: ^2.0.1

  simple_json_mapper:
    git:
      url: git://github.com/sgehrman/simple_json
      path: simple_json_mapper

dev_dependencies:
  build_runner: ^1.12.1
